dist: trusty
language: c
sudo: false

addons:
  apt:
    packages:
      - texinfo

cache:
  directories:
  - work
  - .toolchains

jobs:
  include:
  - stage: setup
    script:
     - make clean
     - make setup
  - stage: binutils
    script:
      - export m68k_prefix=`pwd`/opt/gendev/m68k-elf
      - cd work
      - travis_wait 90 make -f ../gen_gcc/makefile-gen build-m68k-binutils
  - stage: pass1
    script:
      - export m68k_prefix=`pwd`/opt/gendev/m68k-elf
      - cd work
      - travis_wait 90 make -f ../gen_gcc/makefile-gen build-m68k-gcc-pass1
  - stage: newlib
    script:
      - export m68k_prefix=`pwd`/opt/gendev/m68k-elf
      - cd work
      - travis_wait 90 make -f ../gen_gcc/makefile-gen build-m68k-newlib
  - stage: pass2
    script:
      - export m68k_prefix=`pwd`/opt/gendev/m68k-elf
      - cd work
      - travis_wait 90 make -f ../gen_gcc/makefile-gen build-m68k-gcc-pass2
  - stage: sgdk
    script:
      - export GENDEV=`pwd`/opt/gendev
      - make $GENDEV/ldscripts
      - make clean_tools tools
      - make sgdk_clean sgdk_build
      - make deb
      - make gendev.txz

#script:
#  - make setup
  #- travis_wait 90 make toolchain_build GENDEV=".toolchain" SUDO=""
  #  - cd work
  #- travis_wait 90 make -f ../gen_gcc/makefile-gen build-m68k-binutils
  #- travis_wait 90 make -f ../gen_gcc/makefile-gen build-m68k-gcc-pass1
  #- travis_wait 90 make -f ../gen_gcc/makefile-gen build-m68k-newlib
  #- travis_wait 90 make -f ../gen_gcc/makefile-gen build-m68k-gcc-pass2
  #- cd ..
  #- export GENDEV=`pwd`/.toolchain
  #- make $GENDEV/ldscripts
  #- make tools
  #- make sgdk_build
