dist: trusty
language: c
sudo: false

install: texinfo

script:
  - make setup
  - make toolchain_build GENDEV=".toolchain" SUDO=""
  - GENDEV=".toolchain" make .toolchain/ldscripts
  - GENDEV=".toolchain" make tools
  - GENDEV=".toolchain" make sgdk_build
