language: c
sudo: false
script:
  - mkdir /opt/toolchains/gen
  - make setup
  - travis_wait 120 SUDO="" make toolchain_build 
  - make /opt/toolchains/gen/ldscripts
  - make tools
  - make sgdk_build
